---
title: "101c final project"
author: "Wenxin Zhou"
date: "11/23/2019"
output: html_document
---

```{r}
library(class) 
library(ISLR) 
library(MASS) 
library(leaps) 
library(glmnet)
library(pls)
```
#import files
```{r}
train <- read.csv("~/Downloads/fall-2019-stats-101c/train.csv")
test<-read.csv("~/Downloads/fall-2019-stats-101c/test.csv")
#exclude catagorical variable
train<-train[,-c(1,2,4,5,6,7,8)]
test<-test[,-c(1:7)]
train$HTWins<-as.factor(train$HTWins)
```

#PLS
```{r}
pls.fit<-plsr(HTWins ~.,data=train, scale=T, validation="CV")
validationplot(pls.fit, val.type="MSEP")
summary(pls.fit)
pred.pls<-predict(pls.fit,test,ncomp=10,type="response)
predict<-ifelse(pred.pls>0.5,"Yes","No") 
table(predict,test)
```
#PCR
```{r}
model.pcr<-pcr(HTWins~.,data=train,scale=T,validation="CV") 
summary(model.pcr)
validationplot(model.pcr, val.type="MSEP")
pred.pcr<-predict(model.pcr, test,ncomp=10)
predict<-ifelse(pred.pcr>0.5,"Yes","No") 
table(predict,test)
```

```{r}
index <- sample(1:9520,7000,replace = T)
usetrain <- train[index,]
usetest <- train[-index,]
```
```{r}
library(glmnet)
x <- model.matrix(HTWins~.,data = usetrain)
y <- ifelse(usetrain$HTWins=="Yes", 1, 0)

lambda <- 10^seq(10,-2,length=100)
lasso <- glmnet(x,y,alpha = 1,lambda = lambda)
cvlasso <- cv.glmnet(x,y,alpha = 1,lambda = lambda)
plot(cvlasso)
best <- cvlasso$lambda.min
bestlasso <- glmnet(x,y,alpha = 1,lambda = best)
predict<-predict(bestlasso,newx=model.matrix(HTWins~.,data = usetest),s=best,type="response")
p<-ifelse(predict>0.5,"Yes","No")
table(usetest$HTWins,p)
mean(usetest$HTWins == p)
```

```{r}
library(glmnet)
x <- model.matrix(HTWins~.,data = usetrain)
y <- ifelse(usetrain$HTWins=="Yes", 1, 0)

lambda <- 10^seq(10,-2,length=100)
ridge <- glmnet(x,y,alpha = 0,lambda = lambda)
cvridge <- cv.glmnet(x,y,alpha = 0,lambda = lambda)
plot(cvridge)
best <- cvridge$lambda.min
bestridge <- glmnet(x,y,alpha = 0,lambda = best)
predict<-predict(bestridge,newx=model.matrix(HTWins~.,data = usetest),s=best,type="response")
p<-ifelse(predict>0.5,"Yes","No")
table(usetest$HTWins,p)
mean(usetest$HTWins == p)

pred.ridge=predict(bestridge,newx=model.matrix(HTWins~.,data = usetest),type = "response")
```
